import Vue from 'vue'
import Vuetify, {
  VApp, // required
  VNavigationDrawer,
  VFooter,
  VToolbar,
  VToolbarTitle,
  VSpacer,
  VBtn,
  VContent,
  VContainer,
  VLayout,
  VFlex,
  VImg,
  VFadeTransition,
  VCard,
  VToolbarSideIcon,
  VIcon,
  VList,
  VSubheader,
  VListTile,
  VListTileAvatar,
  VListTileContent,
  VListTileTitle,
  VListTileSubTitle,
  VListTileAction,
  VDivider,
  VDialog,
  VCardText,
  VTextField,
  VCardActions,
  VDatePicker,
  VTimePicker,
  VMenu,
  VSelect,
  VForm,
  VCheckbox

} from 'vuetify/lib'

import 'vuetify/src/stylus/app.styl'

Vue.use(Vuetify, {
  iconfont: 'md',
  components: {
    VApp,
    VNavigationDrawer,
    VFooter,
    VToolbar,
    VToolbarTitle,
    VSpacer,
    VBtn,
    VContent,
    VContainer,
    VLayout,
    VFlex,
    VImg,
    VFadeTransition,
    VCard,
    VToolbarSideIcon,
    VIcon,
    VList,
    VListTile,
    VListTileAvatar,
    VListTileContent,
    VListTileTitle,
    VListTileSubTitle,
    VListTileAction,
    VDivider,
    VSubheader,
    VDialog,
    VCardText,
    VTextField,
    VCardActions,
    VDatePicker,
    VTimePicker,
    VMenu,
    VSelect,
    VForm,
    VCheckbox
  }
})
